name: CI/CD_Pipeline

on:
  push:
    branches:
      - main
      - develop
      - testes
  pull_request:
    branches:
      - main
      - develop
  pull_request_target:
    branches:
      - main
      - develop
jobs:
  commit_message_check:  # Verifica a mensagem do commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          REGEX="^((Merge[ a-z-]* branch.*)|(Revert*)|((build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(.*\))?!?: .*))"
          COMMIT_MSGS=$(git log --format=%B ${{ github.event.before }}..${{ github.event.after }})
          echo "$COMMIT_MSGS" | while read -r COMMIT_MSG; do
            if ! echo "$COMMIT_MSG" | grep -Eq "$REGEX"; then
              echo "Commit message does not follow the convention: $COMMIT_MSG"
              exit 1
            fi
          done

  nodejs_build_and_lint:  # Executa a construção e lint do Node.js
    runs-on: ubuntu-latest
    needs: commit_message_check
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 14  # Use a versão LTS do Node.js
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
      - run: npm ci
      - run: npm run lint

  run_tests:  # Executa os testes
    runs-on: ubuntu-latest
    needs: nodejs_build_and_lint
    steps:
      - uses: willcaul/jest-github-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          test-command: "npm test"

  version_generation:  # Gera a versão
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: git configuration
        run: |
          git config --local user.name "Gitactions"
          git config --local user.email "actions@github.com"
      - name: Criação da Versão
        run: |
          npm version patch -m "Bump version to %s"
          git push --follow-tags