name: CI/CD_Pipeline

on:
    pull:
        branches:
            - main
            - develop
    pull_request:
        branches:
            - main
            - develop
    pull_request_targed:
        branches:
            - main
            - develop

            
    